# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: 123
                        roles: 'ROLE_ADMIN'
        user_db:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
            oauth:
#                failure_path: your_path
                login_path: /login
                check_path: /connect_check
                provider: user_db
                resource_owners:
                    facebook: "/login/check-facebook"
#                    google: "/login/check-google"
                oauth_user_provider:
                    service: app.provider.oauth
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/.*, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/myaccount, roles: ROLE_USER }
