services:
    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ["@router"]
    logout_listener:
        class: AppBundle\LogoutListener
        arguments:  ["@security.context"]
    app.provider.oauth:
        class: AppBundle\Security\Core\User\OAuthUserProvider
        arguments: ["@fos_user.user_manager",{facebook: facebookID, google: googleID}]
    app.user_service:
        class: AppBundle\Services\UserService
        arguments: ['@service_container']