#app_admin_user:
#    resource: "@AppBundle/Resources/config/routing/user.yml"
#    prefix:   /admin/user
#login:
#    path: /login
#    defaults: { _controller: AppBundle:Security:login}
#login_check:
#    path: /login_check
#logout:
#    pattern: /logout
